name:                localcooking-db
version:             0.0.0
git:                 "git://git.localcooking.com/localcoooking/localcooking-db.git"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "Copyright (c) 2018 Local Cooking Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/localcooking-db#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.8 && < 5
- localcooking-fb
- localcooking-shared
- aeson
- bytestring
- containers
- emailaddress >= 0.2.0.1
- hashable
- monad-logger
- persistent
- persistent-template
- QuickCheck
- quickcheck-instances
- resourcet
- saltine
- text
- time

library:
  source-dirs: src

tests:
  localcooking-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localcooking-db
    - aeson
    - tasty
    - tasty-hunit
